port: 7890
socks-port: 7891
# redir-port: 7892
mixed-port: 7893
# tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true
tcp-concurrent: true
# interface-name: enp6s18
log-level: info
external-controller: 0.0.0.0:9090
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true
